-- INSERT INTO Ticket (id, status, first_name, last_name, date_of_birth, price, order_id) VALUES (1, 'AVAILABLE', null,   null,   null, 12.99, null);
-- INSERT INTO Ticket (id, status, first_name, last_name, date_of_birth, price, order_id) VALUES (2, 'AVAILABLE', null,   null,   null, 12.99, null);
-- INSERT INTO Ticket (id, status, first_name, last_name, date_of_birth, price, order_id) VALUES (3, 'AVAILABLE', null,   null,   null, 12.99, null);
-- INSERT INTO Ticket (id, status, first_name, last_name, date_of_birth, price, order_id) VALUES (4, 'AVAILABLE', null,   null,   null, 12.99, null);
-- INSERT INTO Ticket (id, status, first_name, last_name, date_of_birth, price, order_id) VALUES (5, 'AVAILABLE', null,   null,   null, 12.99, null);
-- INSERT INTO Ticket (id, status, first_name, last_name, date_of_birth, price, order_id) VALUES (6, 'AVAILABLE', null,   null,   null, 12.99, null);
-- INSERT INTO Ticket (id, status, first_name, last_name, date_of_birth, price, order_id) VALUES (7, 'AVAILABLE', null,   null,   null, 12.99, null);
-- INSERT INTO Ticket (id, status, first_name, last_name, date_of_birth, price, order_id) VALUES (8, 'AVAILABLE', null,   null,   null, 12.99, null);
-- INSERT INTO Ticket (id, status, first_name, last_name, date_of_birth, price, order_id) VALUES (9, 'AVAILABLE', null,   null,   null, 12.99, null);
-- INSERT INTO Ticket (id, status, first_name, last_name, date_of_birth, price, order_id) VALUES (10, 'AVAILABLE', null,   null,   null, 12.99, null);
-- INSERT INTO Ticket (id, status, first_name, last_name, date_of_birth, price, order_id) VALUES (11, 'AVAILABLE', null,   null,   null, 12.99, null);
-- INSERT INTO Ticket (id, status, first_name, last_name, date_of_birth, price, order_id) VALUES (12, 'AVAILABLE', null,   null,   null, 12.99, null);
-- INSERT INTO Ticket (id, status, first_name, last_name, date_of_birth, price, order_id) VALUES (13, 'AVAILABLE', null,   null,   null, 12.99, null);
-- INSERT INTO Ticket (id, status, first_name, last_name, date_of_birth, price, order_id) VALUES (14, 'AVAILABLE', null,   null,   null, 12.99, null);
-- INSERT INTO Ticket (id, status, first_name, last_name, date_of_birth, price, order_id) VALUES (15, 'AVAILABLE', null,   null,   null, 12.99, null);
-- INSERT INTO Ticket (id, status, first_name, last_name, date_of_birth, price, order_id) VALUES (16, 'AVAILABLE', null,   null,   null, 12.99, null);
-- INSERT INTO Ticket (id, status, first_name, last_name, date_of_birth, price, order_id) VALUES (17, 'AVAILABLE', null,   null,   null, 12.99, null);
-- INSERT INTO Ticket (id, status, first_name, last_name, date_of_birth, price, order_id) VALUES (18, 'AVAILABLE', null,   null,   null, 12.99, null);
-- INSERT INTO Ticket (id, status, first_name, last_name, date_of_birth, price, order_id) VALUES (19, 'AVAILABLE', null,   null,   null, 12.99, null);
-- INSERT INTO Ticket (id, status, first_name, last_name, date_of_birth, price, order_id) VALUES (20, 'AVAILABLE', null,   null,   null, 12.99, null);

INSERT INTO Ticket (status, first_name, last_name, date_of_birth, price, order_id, activated) VALUES ('AVAILABLE', null,   null,   null, 12.99, null, false);
INSERT INTO Ticket (status, first_name, last_name, date_of_birth, price, order_id, activated) VALUES ('AVAILABLE', null,   null,   null, 12.99, null, false);
INSERT INTO Ticket (status, first_name, last_name, date_of_birth, price, order_id, activated) VALUES ('AVAILABLE', null,   null,   null, 12.99, null, false);
INSERT INTO Ticket (status, first_name, last_name, date_of_birth, price, order_id, activated) VALUES ('AVAILABLE', null,   null,   null, 12.99, null, false);
INSERT INTO Ticket (status, first_name, last_name, date_of_birth, price, order_id, activated) VALUES ('AVAILABLE', null,   null,   null, 12.99, null, false);
INSERT INTO Ticket (status, first_name, last_name, date_of_birth, price, order_id, activated) VALUES ('AVAILABLE', null,   null,   null, 12.99, null, false);
INSERT INTO Ticket (status, first_name, last_name, date_of_birth, price, order_id, activated) VALUES ('AVAILABLE', null,   null,   null, 12.99, null, false);
INSERT INTO Ticket (status, first_name, last_name, date_of_birth, price, order_id, activated) VALUES ('AVAILABLE', null,   null,   null, 12.99, null, false);
INSERT INTO Ticket (status, first_name, last_name, date_of_birth, price, order_id, activated) VALUES ('AVAILABLE', null,   null,   null, 12.99, null, false);
INSERT INTO Ticket (status, first_name, last_name, date_of_birth, price, order_id, activated) VALUES ('AVAILABLE', null,   null,   null, 12.99, null, false);
INSERT INTO Ticket (status, first_name, last_name, date_of_birth, price, order_id, activated) VALUES ('AVAILABLE', null,   null,   null, 12.99, null, false);
INSERT INTO Ticket (status, first_name, last_name, date_of_birth, price, order_id, activated) VALUES ('AVAILABLE', null,   null,   null, 12.99, null, false);
INSERT INTO Ticket (status, first_name, last_name, date_of_birth, price, order_id, activated) VALUES ('AVAILABLE', null,   null,   null, 12.99, null, false);
INSERT INTO Ticket (status, first_name, last_name, date_of_birth, price, order_id, activated) VALUES ('AVAILABLE', null,   null,   null, 12.99, null, false);
INSERT INTO Ticket (status, first_name, last_name, date_of_birth, price, order_id, activated) VALUES ('AVAILABLE', null,   null,   null, 12.99, null, false);
INSERT INTO Ticket (status, first_name, last_name, date_of_birth, price, order_id, activated) VALUES ('AVAILABLE', null,   null,   null, 12.99, null, false);
INSERT INTO Ticket (status, first_name, last_name, date_of_birth, price, order_id, activated) VALUES ('AVAILABLE', null,   null,   null, 12.99, null, false);
INSERT INTO Ticket (status, first_name, last_name, date_of_birth, price, order_id, activated) VALUES ('AVAILABLE', null,   null,   null, 12.99, null, false);
INSERT INTO Ticket (status, first_name, last_name, date_of_birth, price, order_id, activated) VALUES ('AVAILABLE', null,   null,   null, 12.99, null, false);
INSERT INTO Ticket (status, first_name, last_name, date_of_birth, price, order_id, activated) VALUES ('AVAILABLE', null,   null,   null, 12.99, null, false);