apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: apigateway
  name: apigateway
spec:
  selector:
    matchLabels:
      io.kompose.service: apigateway
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: apigateway
    spec:
      containers:
      - image: lemigom/apigateway
        name: apigateway
        ports:
        - containerPort: 8080
        resources: {}
        volumeMounts:
      restartPolicy: Always
