apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: balance
  name: balance
spec:
  selector:
    matchLabels:
      io.kompose.service: balance
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: balance
    spec:
      containers:
      - image: lemigom/balance
        name: balance
        ports:
        - containerPort: 2228
        resources: {}
        volumeMounts:
      restartPolicy: Always
