apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: display
  name: display
spec:
  selector:
    matchLabels:
      io.kompose.service: display
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: display
    spec:
      containers:
      - image: lemigom/display
        name: display
        ports:
        - containerPort: 2230
        resources: {}
        volumeMounts:
      restartPolicy: Always
