apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: lineup
  name: lineup
spec:
  selector:
    matchLabels:
      io.kompose.service: lineup
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: lineup
    spec:
      containers:
      - image: lemigom/lineup
        name: lineup
        ports:
        - containerPort: 2229
        resources: {}
        volumeMounts:
      restartPolicy: Always
