apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: notification-mongodb
  name: notification-mongodb
spec:
  selector:
    matchLabels:
      io.kompose.service: notification-mongodb
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: notification-mongodb
    spec:
      containers:
      - image: mongo
        name: notification-mongodb
        ports:
        - containerPort: 27017
        resources: {}
      restartPolicy: Always
status: {}
