apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: payment
  name: payment
spec:
  selector:
    matchLabels:
      io.kompose.service: payment
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: payment
    spec:
      containers:
      - image: lemigom/payment
        name: payment
        ports:
        - containerPort: 2232
        resources: {}
        volumeMounts:
      restartPolicy: Always
