apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: security
  name: security
spec:
  selector:
    matchLabels:
      io.kompose.service: security
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: security
    spec:
      containers:
      - image: lemigom/security
        name: security
        ports:
        - containerPort: 2224
        resources: {}
        volumeMounts:
      restartPolicy: Always
