apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: ticket
  name: ticket
spec:
  selector:
    matchLabels:
      io.kompose.service: ticket
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: ticket
    spec:
      containers:
      - image: lemigom/ticket
        name: ticket
        ports:
        - containerPort: 2225
        resources: {}
        volumeMounts:
      restartPolicy: Always
