apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: ticket-postgres
  name: ticket-postgres
spec:
  selector:
    matchLabels:
      io.kompose.service: ticket-postgres
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: ticket-postgres
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          value: ticket
        - name: POSTGRES_PASSWORD
          value: root
        image: postgres
        name: ticket-postgres
        ports:
        - containerPort: 5432
        resources: {}
      restartPolicy: Always
status: {}
